# docker-compose.yml

version: '3.8'

services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    volumes:
      - ./frontend/build:/usr/share/nginx/html  # Monta la build del frontend en el contenedor
    ports:
      - "3000:80"  # Exponer el frontend en el puerto 3000
    networks:
      - app-network

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    volumes:
      - ./backend/models:/app/models             # Monta los modelos en el contenedor
      - ./training:/app/training                 # Monta el código de entrenamiento en el contenedor
    environment:
      - FLASK_ENV=production
    expose:
      - "5000"                                   # Expone el puerto del backend para que Nginx lo use
    networks:
      - app-network

  nginx:
    image: nginx:alpine
    ports:
      - "80:80"                                  # Exponer Nginx en el puerto 80
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf # Monta la configuración de Nginx
      - ./frontend/build:/usr/share/nginx/html   # Monta la build del frontend en Nginx
    depends_on:
      - frontend
      - backend
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
