services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    volumes:
      - ./frontend/build:/usr/share/nginx/html  # Mount the frontend build in the container
    ports:
      - "3000:80"  # Expose the frontend on port 3000
    networks:
      - app-network

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    volumes:
      - ./backend/models:/app/models             # Mount the models in the container
      - ./training:/app/training                 # Mount the training code in the container
    environment:
      - FLASK_ENV=production
    expose:
      - "5000"                                   # Expose the backend port for Nginx
    networks:
      - app-network

  nginx:
    image: nginx:alpine
    ports:
      - "80:80"                                  # Expose Nginx on port 80
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf # Mount the Nginx configuration
      - ./frontend/build:/usr/share/nginx/html   # Mount the frontend build in Nginx
    depends_on:
      - frontend
      - backend
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
